### ISSUE TITLE
Strings in Dropdown Lists not Reloading

### ISSUE THREAD

**Issue by krypto5863** [denikson/IMGUITranslationLoader#1]
Editing strings found in dropdown lists and reloading strings does not reload these strings. It does work for other strings though.

**Comment by ghorsington** [comment]
This is a somewhat intentional payoff for better performance. 

IMGUI Translation Loader does not know how the plug-ins that use IMGUI use the GUI's components: some plug-ins update all components each frame update, while others may cache and reuse some GUI components (like strings). Because of that and concerns for performance, IMGUI Translation Loader does not keep track of any GUI components it encounters, as it cannot possibly determine its life cycle automatically. As a consequence, reloading strings will not always work.

For instance, some plug-ins may cache the strings inside the dropdown menus, which will cause the issue. Since I don't know the specifics of the plgu-in you're trying to translate, I cannot really help further.

More info can be found in the [source code comments](https://github.com/denikson/IMGUITranslationLoader/blob/master/IMGUITranslationLoader.Plugin/IMGUITranslationLoader.cs#L45).

Of course, that does not mean there isn't a possible problem. If you find a plug-in that creates a dropdown inside `OnGUI` without caching the list's elements, please do report about that.
Until I (or you) do find such a plug-in, this issue is closed. 

Do feel free to discuss the issue of retranslating strings even though this issue is marked as closed, as currently I am out of ideas as to how to do that quickly and efficiently.
